# Generated by Django 4.0.1 on 2022-02-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tutor',
            new_name='staff',
        ),
    ]
