# Generated by Django 4.0.1 on 2022-03-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='instructor',
        ),
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.BooleanField(default=True),
        ),
    ]
