# Generated by Django 4.0.1 on 2022-03-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_staff_user_instructor_user_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='instructor',
            new_name='staff',
        ),
    ]
