# Generated by Django 4.0.1 on 2022-03-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student',
        ),
    ]
