# Generated by Django 4.0.1 on 2022-04-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_walletmodel_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
