# Generated by Django 4.0.1 on 2022-04-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_ordermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddressmodel',
            options={'verbose_name': 'Billing Address', 'verbose_name_plural': 'Billing Addresses'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
