# Generated by Django 4.0.1 on 2022-04-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_rename_number_of_kids_sessions_packagemodel_number_of_free_kids_sessions_and_more'),
        ('finance', '0005_remove_ordermodel_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='program.programmodel', verbose_name='class'),
        ),
    ]
