# Generated by Django 4.0.1 on 2022-04-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_rename_number_of_kids_sessions_packagemodel_number_of_free_kids_sessions_and_more'),
        ('finance', '0006_alter_ordermodel_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='package',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='package',
            field=models.ManyToManyField(blank=True, null=True, to='program.PackageModel', verbose_name='package'),
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='program',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='program',
            field=models.ManyToManyField(to='program.ProgramModel', verbose_name='class'),
        ),
    ]
