# Generated by Django 4.0.1 on 2022-05-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_ordermodel_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='kids_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='senior_citizen_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='sessions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
