# Generated by Django 4.0.1 on 2022-05-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_ticketmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketModel',
        ),
    ]
