# Generated by Django 4.0.1 on 2022-02-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTrialOfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone_number', models.CharField(max_length=100, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('created_on', models.TimeField(auto_now_add=True, verbose_name='created on')),
            ],
            options={
                'verbose_name': 'OfferModel',
                'verbose_name_plural': 'OfferModels',
            },
        ),
    ]
