# Generated by Django 4.0.1 on 2022-04-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetrialoffermodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activate'),
        ),
    ]
