# Generated by Django 4.0.1 on 2022-02-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=None, null=None, upload_to='offers/', verbose_name='image')),
                ('title', models.CharField(blank=None, max_length=250, null=None, verbose_name='title')),
                ('created_on', models.TimeField(auto_now_add=True, verbose_name='created on')),
            ],
            options={
                'verbose_name': 'OfferModel',
                'verbose_name_plural': 'OfferModels',
            },
        ),
        migrations.AlterModelOptions(
            name='freetrialoffermodel',
            options={'verbose_name': 'FreeTrialOfferModel', 'verbose_name_plural': 'FreeTrialOfferModels'},
        ),
        migrations.AlterField(
            model_name='freetrialoffermodel',
            name='email',
            field=models.EmailField(blank=None, max_length=254, null=None, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='freetrialoffermodel',
            name='name',
            field=models.CharField(blank=None, max_length=100, null=None, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='freetrialoffermodel',
            name='phone_number',
            field=models.CharField(blank=None, max_length=100, null=None, verbose_name='phone number'),
        ),
    ]
