# Generated by Django 4.0.1 on 2022-02-21 13:03

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offermodel_alter_freetrialoffermodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='content',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
