# Generated by Django 4.0.1 on 2022-02-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_offermodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermodel',
            name='title',
            field=models.CharField(blank=None, max_length=100, null=None, verbose_name='title'),
        ),
    ]
