# Generated by Django 4.0.1 on 2022-02-22 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_alter_offermodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=100, null=None, verbose_name='name')),
                ('email', models.EmailField(blank=None, max_length=254, null=None, verbose_name='email address')),
                ('phone_number', models.CharField(blank=None, max_length=100, null=None, verbose_name='phone number')),
                ('created_on', models.TimeField(auto_now_add=True, verbose_name='created on')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.offermodel', verbose_name='offer')),
            ],
            options={
                'verbose_name': 'BookOfferModel',
                'verbose_name_plural': 'BookOfferModels',
            },
        ),
    ]
