# Generated by Django 4.0.1 on 2022-02-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_bookoffermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookoffermodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='bookoffermodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='bookoffermodel',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='freetrialoffermodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='freetrialoffermodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='freetrialoffermodel',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='offermodel',
            name='image',
            field=models.FileField(upload_to='offers/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='offermodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
