# Generated by Django 4.0.1 on 2022-03-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_alter_bookoffermodel_email_alter_bookoffermodel_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookoffermodel',
            options={'verbose_name': 'Booked Offer', 'verbose_name_plural': 'Booked Offers'},
        ),
        migrations.AlterModelOptions(
            name='freetrialoffermodel',
            options={'verbose_name': 'Free Trial Offer', 'verbose_name_plural': 'Free Trial Offers'},
        ),
        migrations.AlterModelOptions(
            name='offermodel',
            options={'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
    ]
