# Generated by Django 4.0.1 on 2022-03-07 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_alter_bookoffermodel_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookoffermodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='freetrialoffermodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='offermodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on'),
        ),
    ]
