# Generated by Django 4.0.1 on 2022-03-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_alter_bookoffermodel_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activate'),
        ),
    ]
