# Generated by Django 4.0.1 on 2022-03-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_offermodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookoffermodel',
            name='created_on',
        ),
    ]
