# Generated by Django 4.0.1 on 2022-05-07 16:34

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructor', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='program/', verbose_name='image')),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Dance', 'Dance'), ('Fine Arts', 'Fine Arts'), ('Fitness', 'Fitness')], default=('Music', 'Music'), max_length=100, verbose_name='category')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('price', models.FloatField(default=0.0)),
                ('total_space', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True, verbose_name='activate')),
                ('content', tinymce.models.HTMLField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('instructors', models.ManyToManyField(to='instructor.InstructorModel', verbose_name='instructors')),
                ('students', models.ManyToManyField(to='student.StudentModel', verbose_name='students')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='ProgramEnquiryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=100, verbose_name='phone number')),
                ('enquiry', models.TextField(max_length=500, verbose_name='enquiry')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programmodel', verbose_name='class')),
            ],
            options={
                'verbose_name': 'Class Enquiry',
                'verbose_name_plural': 'Class Enquiries',
            },
        ),
        migrations.CreateModel(
            name='ProgramBenefitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(max_length=100, verbose_name='benefit')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programmodel', verbose_name='class')),
            ],
            options={
                'verbose_name': 'Class Benefit',
                'verbose_name_plural': 'Class Benefits',
            },
        ),
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='package/', verbose_name='image')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('initial_price', models.FloatField(default=0.0)),
                ('bonus_price', models.FloatField(default=0.0)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('kids_sessions', models.PositiveIntegerField(default=0)),
                ('senior_citizen_sessions', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='activate')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('program', models.ManyToManyField(to='program.ProgramModel', verbose_name='class')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
