# Generated by Django 4.0.1 on 2022-03-26 15:45

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='program/', verbose_name='image')),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Dance', 'Dance'), ('Fine Arts', 'Fine Arts'), ('Fitness', 'Fitness')], default=('Music', 'Music'), max_length=100, verbose_name='category')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('price', models.PositiveIntegerField()),
                ('total_space', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True, verbose_name='activate')),
                ('calendar', models.DateTimeField(verbose_name='calendar')),
                ('content', tinymce.models.HTMLField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='ProgramPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programmodel', verbose_name='program')),
            ],
            options={
                'verbose_name': 'Program Payment',
                'verbose_name_plural': 'Program Payments',
            },
        ),
        migrations.CreateModel(
            name='ProgramEnquiryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=100, verbose_name='phone number')),
                ('enquiry', models.TextField(max_length=500, verbose_name='enquiry')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programmodel', verbose_name='program')),
            ],
            options={
                'verbose_name': 'Program Enquiry',
                'verbose_name_plural': 'Program Enquiries',
            },
        ),
        migrations.CreateModel(
            name='ProgramBenefitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(max_length=100, verbose_name='benefit')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programmodel', verbose_name='program')),
            ],
            options={
                'verbose_name': 'Program Benefit',
                'verbose_name_plural': 'Program Benefits',
            },
        ),
    ]
