# Generated by Django 4.0.1 on 2022-02-24 11:10

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='program/', verbose_name='image')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('info', tinymce.models.HTMLField()),
                ('created_on', models.TimeField(auto_now_add=True, verbose_name='created on')),
            ],
            options={
                'verbose_name': 'ProgramModel',
                'verbose_name_plural': 'ProgramModels',
            },
        ),
        migrations.CreateModel(
            name='ProgramBenefitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(max_length=100, verbose_name='name')),
                ('created_on', models.TimeField(auto_now_add=True, verbose_name='created on')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programmodel', verbose_name='program')),
            ],
            options={
                'verbose_name': 'ProgramBenefitsModel',
                'verbose_name_plural': 'ProgramBenefitsModels',
            },
        ),
    ]
