# Generated by Django 4.0.1 on 2022-04-14 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programcalendarmodel',
            name='calendar',
        ),
        migrations.AddField(
            model_name='programcalendarmodel',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programcalendarmodel',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start_at'),
            preserve_default=False,
        ),
    ]
