# Generated by Django 4.0.1 on 2022-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_remove_instructormodel_program'),
        ('student', '0002_remove_studentmodel_instructor_and_more'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmodel',
            name='instructors',
            field=models.ManyToManyField(to='instructor.InstructorModel', verbose_name='instructors'),
        ),
        migrations.AddField(
            model_name='programmodel',
            name='students',
            field=models.ManyToManyField(to='student.StudentModel', verbose_name='students'),
        ),
    ]
