# Generated by Django 4.0.1 on 2022-05-31 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagemodel',
            options={'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
    ]
