# Generated by Django 4.0.1 on 2022-02-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_programbenefitmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmodel',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Dance', 'Dance'), ('Fine Arts', 'Fine Arts'), ('Fitness', 'Fitness')], default=('Music', 'Music'), max_length=100, verbose_name='category'),
        ),
    ]
