# Generated by Django 4.0.1 on 2022-04-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_remove_programcalendarmodel_calendar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='bonus_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='packagemodel',
            name='initial_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='programmodel',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
