# Generated by Django 4.0.1 on 2022-04-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_delete_programpaymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemodel',
            name='number_of_kids_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packagemodel',
            name='number_of_senior_citizen_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
