# Generated by Django 4.0.1 on 2022-04-07 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_packagemodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemodel',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='package/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
