# Generated by Django 4.0.1 on 2022-02-24 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_alter_programbenefitmodel_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programbenefitmodel',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programmodel', verbose_name='program'),
        ),
    ]
