# Generated by Django 4.0.1 on 2022-04-09 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_packagemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.DateTimeField(verbose_name='calendar')),
            ],
            options={
                'verbose_name': 'Class Calendar',
                'verbose_name_plural': 'Class Calendars',
            },
        ),
        migrations.AlterModelOptions(
            name='packagemodel',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='programbenefitmodel',
            options={'verbose_name': 'Class Benefit', 'verbose_name_plural': 'Class Benefits'},
        ),
        migrations.AlterModelOptions(
            name='programenquirymodel',
            options={'verbose_name': 'Class Enquiry', 'verbose_name_plural': 'Class Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='programmodel',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='programpaymentmodel',
            options={'verbose_name': 'Class Payment', 'verbose_name_plural': 'Class Payments'},
        ),
        migrations.RemoveField(
            model_name='programmodel',
            name='calendar',
        ),
        migrations.AddField(
            model_name='programmodel',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmodel',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
