# Generated by Django 4.0.1 on 2022-03-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_alter_programbenefitmodel_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programbenefitmodel',
            options={'verbose_name': 'Program Benefit', 'verbose_name_plural': 'Program Benefits'},
        ),
        migrations.AlterModelOptions(
            name='programenquirymodel',
            options={'verbose_name': 'Program Enquiry', 'verbose_name_plural': 'Program Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='programmodel',
            options={'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
    ]
