# Generated by Django 4.0.1 on 2022-04-26 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_rename_number_of_kids_sessions_packagemodel_number_of_free_kids_sessions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagemodel',
            old_name='number_of_free_kids_sessions',
            new_name='kids_sessions',
        ),
        migrations.RenameField(
            model_name='packagemodel',
            old_name='number_of_free_senior_citizen_sessions',
            new_name='senior_citizen_sessions',
        ),
    ]
