# Generated by Django 4.0.1 on 2022-04-09 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_delete_programcalendar_alter_packagemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagemodel',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='programbenefitmodel',
            options={'verbose_name': 'Class Benefit', 'verbose_name_plural': 'Class Benefits'},
        ),
        migrations.AlterModelOptions(
            name='programenquirymodel',
            options={'verbose_name': 'Class Enquiry', 'verbose_name_plural': 'Class Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='programmodel',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='programpaymentmodel',
            options={'verbose_name': 'Class Payment', 'verbose_name_plural': 'Class Payments'},
        ),
        migrations.RemoveField(
            model_name='programmodel',
            name='calendar',
        ),
        migrations.AddField(
            model_name='programmodel',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start time'),
            preserve_default=False,
        ),
    ]
