# Generated by Django 4.0.1 on 2022-03-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_alter_programbenefitmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmodel',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
