# Generated by Django 4.0.1 on 2022-04-09 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_alter_packagemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmodel',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end time'),
            preserve_default=False,
        ),
    ]
