# Generated by Django 4.0.1 on 2022-05-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_packagemodel_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
