# Generated by Django 4.0.1 on 2022-04-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_remove_programmodel_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmodel',
            name='start_time',
        ),
        migrations.CreateModel(
            name='ProgramCalendarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.DateTimeField(verbose_name='calendar')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programmodel', verbose_name='class')),
            ],
            options={
                'verbose_name': 'Class Calendar',
                'verbose_name_plural': 'Class Calendars',
            },
        ),
    ]
