# Generated by Django 4.0.1 on 2022-03-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_alter_programbenefitmodel_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmodel',
            name='total_space',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
