# Generated by Django 4.0.1 on 2022-03-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_programpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programpayment',
            options={'verbose_name': 'Program Payment', 'verbose_name_plural': 'Program Payments'},
        ),
    ]
