# Generated by Django 4.0.1 on 2022-03-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_rename_programpayment_programpaymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
