# Generated by Django 4.0.1 on 2022-03-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_programmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programbenefitmodel',
            name='benefit',
            field=models.CharField(max_length=100, verbose_name='benefit'),
        ),
        migrations.AlterField(
            model_name='programenquirymodel',
            name='enquiry',
            field=models.TextField(max_length=500, verbose_name='enquiry'),
        ),
        migrations.AlterField(
            model_name='programmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activate'),
        ),
    ]
