# Generated by Django 4.0.1 on 2022-03-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0016_alter_programbenefitmodel_benefit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgramEnquiryModel',
        ),
    ]
