# Generated by Django 4.0.1 on 2022-03-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0018_programenquirymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmodel',
            old_name='info',
            new_name='content',
        ),
    ]
