# Generated by Django 4.0.1 on 2022-03-26 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0019_rename_info_programmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmodel',
            name='calendar',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='calendar'),
            preserve_default=False,
        ),
    ]
