# Generated by Django 4.0.1 on 2022-04-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructormodel',
            name='program',
        ),
    ]
