# Generated by Django 4.0.1 on 2022-02-22 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructormodel',
            name='role',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructormodel',
            name='avatar',
            field=models.FileField(upload_to='avatar/', verbose_name='avatar'),
        ),
    ]
