# Generated by Django 4.0.1 on 2022-05-31 15:51

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_msg', tinymce.models.HTMLField(blank=True, null=True)),
                ('schedule_on', models.DateTimeField(blank=True, null=True, verbose_name='schedule on')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.instructormodel', verbose_name='instructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmodel', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
            },
        ),
    ]
