# Generated by Django 4.0.1 on 2022-04-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructormodel',
            name='comission',
        ),
        migrations.RemoveField(
            model_name='instructormodel',
            name='salary',
        ),
    ]
