# Generated by Django 4.0.1 on 2022-05-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_instructornotificationmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructornotificationmodel',
            options={'verbose_name': 'Instructor Notification', 'verbose_name_plural': 'Instructor Notifications'},
        ),
    ]
