# Generated by Django 4.0.1 on 2022-04-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_packagemodel_is_active'),
        ('instructor', '0002_alter_instructormodel_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructormodel',
            name='program',
            field=models.ManyToManyField(to='program.ProgramModel', verbose_name='program'),
        ),
    ]
