# Generated by Django 4.0.1 on 2022-02-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_alter_programbenefitmodel_program'),
        ('instructor', '0002_alter_instructormodel_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructormodel',
            name='program',
        ),
        migrations.AddField(
            model_name='instructormodel',
            name='program',
            field=models.ManyToManyField(to='program.ProgramModel', verbose_name='program'),
        ),
    ]
