# Generated by Django 4.0.1 on 2022-02-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_remove_instructormodel_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructormodel',
            name='avatar',
        ),
    ]
