# Generated by Django 4.0.1 on 2022-04-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_packagemodel_image'),
        ('instructor', '0003_alter_instructormodel_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructormodel',
            name='comission',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructormodel',
            name='salary',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructormodel',
            name='program',
            field=models.ManyToManyField(to='program.ProgramModel', verbose_name='class'),
        ),
    ]
