# Generated by Django 4.0.1 on 2022-06-01 13:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_alter_instructornotificationmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructornotificationmodel',
            name='instructor_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructornotificationmodel',
            name='student_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructornotificationmodel',
            name='instructor_msg',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='message'),
        ),
    ]
