# Generated by Django 4.0.1 on 2022-03-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_remove_instructormodel_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructormodel',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
    ]
