# Generated by Django 4.0.1 on 2022-03-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0008_alter_instructormodel_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructormodel',
            name='created_on',
        ),
    ]
