# Generated by Django 4.0.1 on 2022-03-13 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0009_remove_instructormodel_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructormodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created on'),
            preserve_default=False,
        ),
    ]
