# Generated by Django 4.0.1 on 2022-05-15 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructor', '0001_initial'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Gymnastic', 'Gymnastic'), ('Yoga', 'Yoga'), ('Art', 'Art')], default=('Music', 'Music'), max_length=100, verbose_name='category')),
                ('listing', models.CharField(max_length=100, verbose_name='listing')),
                ('coming_soon', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
            },
        ),
        migrations.CreateModel(
            name='StudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
            ],
            options={
                'verbose_name': 'Studio',
                'verbose_name_plural': 'Studios',
            },
        ),
        migrations.CreateModel(
            name='StudioUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full name')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studiomodel', verbose_name='studio')),
            ],
            options={
                'verbose_name': 'Studio User',
                'verbose_name_plural': 'Studio Users',
            },
        ),
        migrations.CreateModel(
            name='CalendarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='start_at')),
                ('end_at', models.DateTimeField(verbose_name='end_at')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.instructormodel', verbose_name='instructor')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programmodel', verbose_name='class')),
            ],
            options={
                'verbose_name': 'Class Calendar',
                'verbose_name_plural': 'Class Calendars',
            },
        ),
    ]
