# Generated by Django 4.0.1 on 2022-04-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('program', '__first__'),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarmodel',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.instructormodel', verbose_name='instructor'),
        ),
        migrations.AddField(
            model_name='calendarmodel',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programmodel', verbose_name='class'),
        ),
    ]
