# Generated by Django 4.0.1 on 2022-03-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_listingmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='coming_soon',
            field=models.BooleanField(default=False),
        ),
    ]
