# Generated by Django 4.0.1 on 2022-04-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_whitelistmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhiteListModel',
        ),
    ]
