# Generated by Django 4.0.1 on 2022-02-25 10:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutmodel_about_alter_aboutmodel_mission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='about',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='mission',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='value',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='vision',
            field=tinymce.models.HTMLField(),
        ),
    ]
