# Generated by Django 4.0.1 on 2022-03-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutmodel_about_alter_aboutmodel_mission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
    ]
