# Generated by Django 4.0.1 on 2022-03-07 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_aboutmodel_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on'),
        ),
    ]
