# Generated by Django 4.0.1 on 2022-03-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_aboutmodel_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='about',
        ),
    ]
