# Generated by Django 4.0.1 on 2022-03-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_remove_aboutmodel_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='created_on',
        ),
    ]
