# Generated by Django 4.0.1 on 2022-03-16 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0010_instructormodel_created_on'),
        ('program', '0019_rename_info_programmodel_content'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='program',
            field=models.ManyToManyField(to='program.ProgramModel', verbose_name='program'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.instructormodel', verbose_name='instructor'),
        ),
    ]
