# Generated by Django 4.0.1 on 2022-04-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='program',
        ),
    ]
