# Generated by Django 4.0.1 on 2022-05-07 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, max_length=8, verbose_name='date of birth'),
            preserve_default=False,
        ),
    ]
