# Generated by Django 4.0.1 on 2022-04-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_remove_instructormodel_comission_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='instructor',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='instructor',
            field=models.ManyToManyField(to='instructor.InstructorModel', verbose_name='instructor'),
        ),
    ]
