# Generated by Django 4.0.1 on 2022-05-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentmodel_address_studentmodel_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='dob',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='date of birth'),
        ),
    ]
