# Generated by Django 4.0.1 on 2022-04-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_studentmodel_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='kid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='senior_citizen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='sessions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
