# Generated by Django 4.0.1 on 2022-03-21 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0012_alter_instructormodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0003_alter_studentmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructor.instructormodel', verbose_name='instructor'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
