# Generated by Django 4.0.1 on 2022-04-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentmodel_kid_studentmodel_senior_citizen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='kid',
            new_name='kids',
        ),
    ]
